apiVersion: v1
kind: Service
metadata:
  name: bookstore-api-aggregate
spec:
  type: NodePort
  selector:
    app: bookstore-api-aggregate
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-api-aggregate
  labels:
    app: bookstore-api-aggregate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-api-aggregate
  template:
    metadata:
      labels:
        app: bookstore-api-aggregate
    spec:
      containers:
        - name: bookstore-api-aggregate
          image: bookstore-api-aggregate_dev
          imagePullPolicy: Never
          command: ['npm', 'run', 'start:prod']
          ports:
            - containerPort: 3000
          env:
            - name: CORE_API_URL
              value: http://bookstore-api:8080
            - name: PRODUCT_API_URL
              value: http://bookstoreapiproducts:8002/api         
